"""Hacer tecnico_id nullable en ordenes

Revision ID: 8dc5a87660f4
Revises: f79382490ba2
Create Date: 2025-05-24 09:34:04.340419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8dc5a87660f4'
down_revision = 'f79382490ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('tecnico_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('tecnico_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
