"""Agregar campo correo_encargado a SolicitudCotizacion

Revision ID: 92297b303a43
Revises: 2855eeb658c9
Create Date: 2025-05-22 00:01:47.944834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92297b303a43'
down_revision = '2855eeb658c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correo_log', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)

    with op.batch_alter_table('solicitud_cotizacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo_encargado', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_cotizacion', schema=None) as batch_op:
        batch_op.drop_column('correo_encargado')

    with op.batch_alter_table('correo_log', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)

    # ### end Alembic commands ###
