"""Agregar tabla ordenes_eliminadas

Revision ID: c11b0867ba2b
Revises: 126817a8bb9a
Create Date: 2025-05-25 23:07:36.509328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c11b0867ba2b'
down_revision = '126817a8bb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_eliminadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id_original', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=100), nullable=True),
    sa.Column('cliente_correo', sa.String(length=120), nullable=True),
    sa.Column('equipo', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion_original', sa.DateTime(), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=False),
    sa.Column('eliminado_por', sa.String(length=100), nullable=False),
    sa.Column('motivo_eliminacion', sa.Text(), nullable=True),
    sa.Column('datos_adicionales', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordenes_eliminadas')
    # ### end Alembic commands ###
