"""Agregar relacion con cliente2

Revision ID: e1ed561e725b
Revises: 92297b303a43
Create Date: 2025-05-22 00:37:20.652915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1ed561e725b'
down_revision = '92297b303a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
